name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
  pull_request: # 在main分支合并别人提的pr时
    branches:
      - main

# 添加权限配置
permissions:
  contents: read
  pages: write
  id-token: write

jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4 # 更新到最新版本
        with:
          fetch-depth: 0 # 获取完整的git历史
      
      - uses: actions/setup-python@v5 # 更新到最新版本
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      
      - name: Build site
        run: mkdocs build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
